### ISSUE TITLE
organization---make separate directories for each web site

### ISSUE THREAD

**Issue by cckuhlman** [hcars/net.science_datasets#2]
Make separate directories for each of the web sites you visit, e.g., mark_newmann.

Under there, have the edge lists, the mapping files, node and edge attributes, etc.

This way, we group by URL.

Codes can be in separate directories, if they are agnostic to the particular URL.

You may already have this, Henry, and so you are way ahead of me.  I just did not see it.  I might be missing something.

**Comment by cckuhlman** [comment]
It looks like you have done this now.

Also, please put ravi on this repo, if possible.

thanks.

**Comment by hcars** [comment]
I've invited Ravi, and reorganized the files based on which website they came from.
